kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # See https://kind.sigs.k8s.io/docs/user/configuration/ for more details
  extraPortMappings:
  # Will map port 80 on this node to port 8080 on the host
  - containerPort: 80 
    hostPort: 8080
    protocol: TCP
    listenAddress: 0.0.0.0 # this is default 
  # Will map port 443 on this node to port 8443 on the host
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
    listenAddress: 0.0.0.0